allow more than one SWT on a server

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -30,10 +30,12 @@
 # THVV 02/18/21 move all file checking to checkswtfiles
 # THVV 03/20/21 fix up the XDOMAINS stuff
 # THVV 06/20/21 Eric Swenson pointed out many weaknesses.  Added checks to check for correct installation, especially of Perl.
+# THVV 06/14/22 Moving pl362 to Ubuntu found some bugs. Fix setting DATABASE in cronjob.
+# THVV 07/15/22 fixes so that one web server can have different instances of swt that use different databases.
 
 # bugs
 # ... should write out as soon as all questions are answered so if anything is not set, we don't have to do it all again
-# ... need not have expandfile readapacheline.pm thvve.pm in the execution directory if they are on the path ??? 
+# ... cannot have different SWT installations use different versions of expandfile
 # ... -geoip different from -geoipcity in logextractor2, make sure doing this right, check the geoipfilename .. oops, doesnt work that way
 
 # ----------------------------------------------------------------
@@ -80,7 +82,7 @@ fi
 # .. on pre-Big Sur macs, the system perl was very ancient
 whereisperl=`which /usr/local/bin/perl`
 if [ "$whereisperl" = "" ] ; then
-    echo 1>&2 "$0: ***** failed: /usr/local/bin/perl not found. Shebang lines in tools will fail."
+    echo 1>&2 "$0: ***** failed: /usr/local/bin/perl not found. Shebang lines in /tools will fail."
     exit 127
 fi
 # PERL5LIB must be defined
@@ -159,7 +161,7 @@ else
 fi
 
 # ----------------------------------------------------------------
-# ask a lot of questions
+# functions to ask a lot of questions
 # .. if user enters a blank line, set it to the default
 # .. if default is "", ask again until nonblank is entered
 # .. if result is -blank- then we meant ""
@@ -340,6 +342,22 @@ askforexistingdir()
     cd $curdir
     export ${thing}=$newdir
 } # askforexistingdir
+
+# ================================================================
+# functions to check tools vs installed $HOME/bin files .. prints warnings if different
+checkvsbin()
+{
+    local thing=""
+    thing="$1"
+    echo "$0: checking that tools/$thing and $HOME/bin/$thing match..."
+    diff -b $HOME/bin/$thing tools/$thing
+    if [ $? != 0 ] ; then
+	echo "$0: **** warning: diff $HOME/bin/$thing tools/$thing; resolve ****"
+	echo "## `date` $HOME/bin/$thing differs from install-swt/tools/$thing" >> CONFIGURE.status
+    else
+	echo "## `date` configure $HOME/bin/$thing ok" >> CONFIGURE.status
+    fi
+} # checkvsbin
 
 # ================================================================
 # constants
@@ -581,6 +599,19 @@ fi
 rm CONFIGURE.temp.sql
 #
 echo "================================================================"
+# ensure that the right stuff is installed in $HOME/bin .. tools should match .. differences are warnings not fatal
+checkvsbin expandfile
+checkvsbin expandfile.pm
+checkvsbin readbindsql.pm
+checkvsbin readbindxml.pm
+checkvsbin databasesize.pm
+checkvsbin readapacheline.pm
+checkvsbin dbsize
+checkvsbin fmtnum
+checkvsbin padstring
+checkvsbin logextractor2
+
+echo "================================================================"
 echo "$0: testing that expandfile can expand a template..."
 rm -f swtconfig.htmi
 expandfile CONFIGURE.swtconfig.htmi.tpt > swtconfig.htmi
@@ -675,22 +706,23 @@ rm -f sql.cnf mysqlload mysqlrun mys mysqldumpcum
 expandfile swtconfig.htmi CONFIGURE.sqlcnf.tpt > sql.cnf
 chmod 400 sql.cnf
 
-echo "$0: .. generating mysqlload mys msqlrun mysqldumpcum in tools/"
+# these files cannot live in /tools, since they are tailored to the database and a site may have several SWTs
+echo "$0: .. generating mysqlload mys msqlrun mysqldumpcum"
 if [ "$OLDMYSQL" = "yes" ] ; then
     echo "$0: old style SQL OLDMYSQL=$OLDMYSQL"
-    expandfile swtconfig.htmi CONFIGURE.oldmysqlload.tpt > tools/mysqlload
-    expandfile swtconfig.htmi CONFIGURE.oldmysqlrun.tpt > tools/mysqlrun
-    expandfile swtconfig.htmi CONFIGURE.oldmys.tpt > tools/mys
-    expandfile swtconfig.htmi CONFIGURE.oldmysqldumpcum.tpt > tools/mysqldumpcum
+    expandfile swtconfig.htmi CONFIGURE.oldmysqlload.tpt > mysqlload
+    expandfile swtconfig.htmi CONFIGURE.oldmysqlrun.tpt > mysqlrun
+    expandfile swtconfig.htmi CONFIGURE.oldmys.tpt > mys
+    expandfile swtconfig.htmi CONFIGURE.oldmysqldumpcum.tpt > mysqldumpcum
 else
     echo "$0: new style SQL OLDMYSQL=$OLDMYSQL"
-    expandfile swtconfig.htmi CONFIGURE.mysqlload.tpt > tools/mysqlload
-    expandfile swtconfig.htmi CONFIGURE.mysqlrun.tpt > tools/mysqlrun
-    expandfile swtconfig.htmi CONFIGURE.mys.tpt > tools/mys
-    expandfile swtconfig.htmi CONFIGURE.mysqldumpcum.tpt > tools/mysqldumpcum
+    expandfile swtconfig.htmi CONFIGURE.mysqlload.tpt > mysqlload
+    expandfile swtconfig.htmi CONFIGURE.mysqlrun.tpt > mysqlrun
+    expandfile swtconfig.htmi CONFIGURE.mys.tpt > mys
+    expandfile swtconfig.htmi CONFIGURE.mysqldumpcum.tpt > mysqldumpcum
 fi
 # need x permission, may contain passwords, secure correctly
-chmod 500 tools/mysqlload tools/mysqldumpcum tools/mysqlrun tools/mys
+chmod 500 mysqlload mysqldumpcum mysqlrun mys
 
 # uses $MYDOMAIN, $SITENAME, $SITEID, $CONFIGFILEDIR, $PROGRAMDIR, $DATADIR, $XDOMAINS
 echo "$0: .. generating swt-user.sql"
@@ -725,14 +757,14 @@ expandfile swtconfig.htmi CONFIGURE.check-tables.tpt > CONFIGURE.check-tables.sq
 # generate geoip2.sh.  Uses MAXMIND_LICENSE_KEY
 if test $GEOIP = "yes"
 then
-    message "generating tools/geoip2.sh"
+    message "generating geoip2.sh"
     # if the license key is not set in shell config, set it
     test -z "$MAXMIND_LICENSE_KEY" && export MAXMIND_LICENSE_KEY="MAXMIND_LICENSE_KEY"
-    expandfile swtconfig.htmi CONFIGURE.geoip2.sh.tpt > tools/geoip2.sh
-    chmod +x tools/geoip2.sh
+    expandfile swtconfig.htmi CONFIGURE.geoip2.sh.tpt > geoip2.sh
+    chmod +x geoip2.sh
     # if the license key is the default, remind user to get a real one
     if [ "$MAXMIND_LICENSE_KEY" = "MAXMIND_LICENSE_KEY" ] ; then
-	echo "***** edit tools/geoip2.sh to replace MAXMIND_LICENSE_KEY, see https://dev.maxmind.com/geoip/geoip2/geolite2/"
+	echo "***** edit geoip2.sh to replace MAXMIND_LICENSE_KEY, see https://dev.maxmind.com/geoip/geoip2/geolite2/"
     fi
 fi
 
diff --git a/tools/checkswtfiles b/tools/checkswtfiles
--- a/tools/checkswtfiles
+++ b/tools/checkswtfiles
@@ -14,7 +14,9 @@
 # THVV 03/18/21 add tarfile-manifest.e to install-needs
 # THVV 03/26/21 adjust list of templates to match swt.sql
 # THVV 04/08/21 remove filetypepie.htmt and pienumberfile, obsolete
-# THVV 06/11/21 expandfile3 => expandfile
+# THVV 06/11/21 expandfile3 renamed expandfile
+# THVV 06/13/22 do not require globalqueries.htmt
+# THVV 07/14/22 check mys, mysqlrun, mysqldumpcum, mysqlload in prerun
 # ----------------------------------------------------------------
 # checks dirs
 #  SWTDIR          htmx files and sql files
@@ -37,8 +39,10 @@ elif [ "$FUNCTION" = "-preconfig" ] ; then
     CONFIGDIR=$SWTDIR
     RUNTIMEDIR="live/"
 elif [ "$FUNCTION" = "-preinstall" ] ; then
+    CONFIGDIR=$SWTDIR
     RUNTIMEDIR="live/"
 elif [ "$FUNCTION" = "-prerun" ] ; then
+    CONFIGDIR=$SWTDIR
     RUNTIMEDIR=$1
     RUNTIMEDIR="$RUNTIMEDIR"/		# ensure one trailing slash
     RUNTIMEDIR=`echo $RUNTIMEDIR | sed -e 's://$:/:'`
@@ -50,6 +54,7 @@ else
     echo "USAGE: sh checkswtfiles -preconfig|-preinstall|-prerun RUNTIMEDIR"
     exit 1  
 fi
+echo "$0: $FUNCTION check in `pwd`"
 
 filepresent()
 {
@@ -64,24 +69,34 @@ checkalist()
 {
     local a_pfx=""
     a_pfx="$1/"
+    if [ "$a_pfx" = "/" ] ; then
+	echo "$0: oops, error, a_pfx is empty"
+	exit 12
+    fi
     local a_list=""
     a_list="$2"
+    if [ "$a_list" = "" ] ; then
+	echo "$0: oops, error, a_list is empty"
+	exit 12
+    fi
     for i in $a_list
     do
 	filepresent $a_pfx$i
     done
 }
 
-templates=" accesstime.htmt analysis.htmt attacks.htmt byyear.htmt config.htmt cumdom.htmt cumpage.htmt dashcsv.htmt diskmontpt.htmt domain1.htmt domainlevel.htmt dslvhist.htmt duration.htmt filelist.htmt filesize.htmt filetype1.htmt geoloc.htmt ggq.htmt globalconfig.htmt globalqueries.htmt google.htmt heading.htmt histo2n.htmt histo3n1.htmt histo3nn1.htmt illref.htmt important7dayhead.htmt importanthead.htmt importanttail.htmt importantwrapper.htmt info.htmt localquery.htmt longshort.htmt monthsum.htmt navlinks.htmt optdoc.htmt paths1.htmt pathsql.htmt piecharts.htmt queries.htmt referrer.htmt repeat.htmt report403.htmt retcodetable.htmt tail.htmt todayline.htmt verbtable.htmt vhisto.htmt visitdetailhead.htmt visitsbycount.htmt wtxmacros.htmi yquery.htmt yreferrer.htmt ywords.htmt"
+templates=" accesstime.htmt analysis.htmt attacks.htmt byyear.htmt config.htmt cumdom.htmt cumpage.htmt dashcsv.htmt diskmontpt.htmt domain1.htmt domainlevel.htmt dslvhist.htmt duration.htmt filelist.htmt filesize.htmt filetype1.htmt geoloc.htmt ggq.htmt globalconfig.htmt google.htmt heading.htmt histo2n.htmt histo3n1.htmt histo3nn1.htmt illref.htmt important7dayhead.htmt importanthead.htmt importanttail.htmt importantwrapper.htmt info.htmt localquery.htmt longshort.htmt monthsum.htmt navlinks.htmt optdoc.htmt paths1.htmt pathsql.htmt piecharts.htmt queries.htmt referrer.htmt repeat.htmt report403.htmt retcodetable.htmt tail.htmt todayline.htmt verbtable.htmt vhisto.htmt visitdetailhead.htmt visitsbycount.htmt wtxmacros.htmi yquery.htmt yreferrer.htmt ywords.htmt"
 
 parts=" configdisplay.htmx swt swt.sql swtfunct.sh wtxmacros.htmi"
 
-toolsfiles="expandfile expandfile.pm readbindsql.pm readbindxml.pm checkswtfiles combinelogs expandfile_config logmerge logvisits3.pl mys mysqlrun mysqlload mysqldumpcum printvisitdetail3.pl readapacheline.pm thvvutil3.pm visitdata3.pl wordlist3.pl"
+toolsfiles="checkswtfiles combinelogs expandfile_config logmerge logvisits3.pl printvisitdetail3.pl readapacheline.pm thvvutil3.pm visitdata3.pl wordlist3.pl"
 
 config_templates=" combinelogs.conf configure CONFIGURE.swtconfig.htmi.tpt CONFIGURE.sqlcnf.tpt CONFIGURE.oldmys.tpt CONFIGURE.oldmysqldumpcum.tpt CONFIGURE.oldmysqlload.tpt CONFIGURE.oldmysqlrun.tpt CONFIGURE.mys.tpt CONFIGURE.mysqldumpcum.tpt CONFIGURE.mysqlload.tpt CONFIGURE.swt-user-sql.tpt CONFIGURE.check-tables.tpt CONFIGURE.mysqlrun.tpt CONFIGURE.cronjob.tpt CONFIGURE.combining-cronjob.tpt CONFIGURE.combinelogs-conf.tpt filecleanupsh.tpt install tablecleanupsql.tpt"
 
-config_results="swt-user.sql mys mysqlrun mysqlload mysqldumpcum sql.cnf sqlx.cnf"
+# retults of configure, s/b in $CONFIGDIR => $SWTDIR
+config_results="swt-user.sql mys mysqlrun mysqlload mysqldumpcum sql.cnf"
 
+# intialization in $CONFIGDIR
 install_needs="init_wtcumfile.sql init_wtcumgoog.sql init_wtcumpath.sql init_wtcumquery.sql init_wtcumref.sql init_wtdayhist.sql init_wtdomhist.sql init_wtlog.sql init_wtsrhist.sql tarfile-manifest.e"
 
 runtimefiles="blackpix.gif bluepix.gif cyanpix.gif darkbluepix.gif fuchsiapix.gif goldenrodpix.gif graypix.gif greenpix.gif indigopix.gif lightgreenpix.gif limepix.gif maroonpix.gif navypix.gif olivepix.gif orangepix.gif pinkpix.gif purplepix.gif redpix.gif silverpix.gif tealpix.gif violetpix.gif whitepix.gif yellowpix.gif swt.js piecanvas.js excanvas.js swtstyle.css"
@@ -112,12 +127,18 @@ if [ "$CONFIGDIR" != "" ] ; then
     checkalist "$CONFIGDIR" "$config_templates"
 fi
 
-# .. for -preinstall, check configure results and intialization .sql files
+# .. for -preinstall, check configure results and intialization .sql files are in install-swt
 if [ "$FUNCTION" = "-preinstall" ] ; then
     #.. check that configure worked
     checkalist "$CONFIGDIR" "$config_results"
     #.. check install machinery
     checkalist "$CONFIGDIR" "$install_needs"
+fi
+
+# .. for -prerun, check the myxxx tools are actually installed
+if [ "$FUNCTION" = "-prerun" ] ; then
+    #.. check that configure worked for myxxx tools
+    checkalist "$SWTDIR" "$config_results"
 fi
 
 # .. check runtime gifs etc
@@ -194,7 +215,7 @@ fi
 # ----------------------------------------------------------------
 # complain if anything was missing and return nonzero errcode
 # ----------------------------------------------------------------
-echo "$0: checked $nfiles files."
+echo "$0: $FUNCTION checked $nfiles files in `pwd`."
 if test ! -z "$BAD"
 then
     { echo "$0: missing files: $BAD" >&2
